name: Java CI with Gradle (TreeWalk & History)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        project: [ "TreeWalker", "History" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle Wrapper Executable
        run: chmod +x ${{ matrix.project }}/gradlew

      - name: Build & Test ${{ matrix.project }}
        working-directory: ${{ matrix.project }}
        run: ./gradlew build
